name: Build and Deploy - be-feed

on:
  push:
    paths:
      - 'be-feed/**'
env:
  SERVICE_NAME: be-feed  # 👈 这里设置的是全局环境变量


jobs:
  build-be-feed:
    if: github.repository == 'asynccnu/ccnubox-be'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          registry: crpi-vgud82zncz8nwfuc.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Build and push image
        run: |
          chmod +x ./scripts/build-${SERVICE_NAME}.sh
          ./scripts/build-${SERVICE_NAME}.sh ${{ secrets.IMAGE_REPO }}

